# Site settings
title: My Awesome Project
description: Documentation and guides for my project.
# Build settings
markdown: kramdown  # Use kramdown as the Markdown engine (recommended)
theme: minima       # Or your preferred Jekyll theme

# Permalinks (controls how URLs are generated)
permalink: pretty     # Use pretty permalinks (e.g., /docs/installation/)

# Plugins (enable useful Jekyll plugins)
plugins:
  - jekyll-feed        # Generate an Atom feed for blog posts
  - jekyll-sitemap     # Generate a sitemap.xml for search engines
  - jekyll-seo-tag     # Add SEO meta tags

# Exclude (prevent Jekyll from processing certain files/folders)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


defaults: # Set default values for pages and posts
  - scope:
      path: "" # empty string for all files
      type: "posts" # apply to posts
    values:
      layout: "post"
  - scope:
      path: "docs" # Docs folder
      type: "pages" # apply to pages
    values:
      layout: "default" # Use the 'default' layout for pages in the 'docs' folder

# Other settings
future: true         # Show future-dated posts
